# Introduction

## 1- Say "Hello, World!" with Python

In [1]:
print("Hello, World!")

Hello, World!


## 2- Python If-Else

In [4]:
n = 5
if n%2 == 1 :
    print("Weird")
else :
    if n >= 2 and n <= 5 or n > 20 :
        print("Not Weird")
    else :
        print("Weird")

Weird


## 3- Arithmetic Operators

In [6]:
a = 3
b = 2
print(a+b)
print(a-b)
print(a*b)

5
1
6


## 4- Python: Division

In [9]:
a = 4
b = 3
print(a//b)
print(a/b)

1
1.3333333333333333


## 5- Loops

In [10]:
n = 5
for i in range (n) :
    print(i*i)

0
1
4
9
16


## 6- Write a function

In [11]:
def is_leap(year):
    leap = False
    
    if year%4 == 0 :
        if year%100 == 0 :
            if year%400 == 0 :
                leap = True
        else :
            leap = True
    
    return leap

year = 1990
print(is_leap(year))

False


## 7- Print Function

In [15]:
n = 5
for i in range (1, n+1) :
    print(i, end='')

12345

# 

# Data types

## 1- List Comprehensions

In [25]:
import itertools

x = 1
y = 1
z = 2
n = 3
print([[i,j,k] for i in range(x+1) for j in range(y+1) for k in range(z+1) if i+j+k!=n])


[[0, 0, 0], [0, 0, 1], [0, 0, 2], [0, 1, 0], [0, 1, 1], [1, 0, 0], [1, 0, 1], [1, 1, 0], [1, 1, 2]]


## 2- Find the Runner-Up Score!

In [2]:
n = 5
arr = map(int, '2 3 6 6 5'.split())
L = list(set(arr))
L.sort()
print(L[-2])

5


## 3- Nested Lists

In [2]:
scores = []
records = []
for i in range(int(input())):
    name = input()
    score = float(input())
    scores.append(score)
    records.append([name,score])
scores = list(set(scores))
scores.sort()
second_lowest_score = scores[1]
names_second_lowest_score = []
for record in records :
    if record[1] == second_lowest_score :
        names_second_lowest_score.append(record[0])
names_sorted = list(set(names_second_lowest_score))
names_sorted.sort()
for name in names_sorted :
    print(name)

5
Harry
37.21
Berry
37.21
Tina
37.2
Akriti
41
Harsh
39
Berry
Harry


## 4- Finding the percentage

In [3]:
n = int(input())
student_marks = {}
for _ in range(n):
    name, *line = input().split()
    scores = list(map(float, line))
    student_marks[name] = scores
query_name = input()
marks = student_marks[query_name]
mean = sum(marks)/len(marks)
print(f"{mean:.2f}")

2
Harsh 25 26.5 28
Anurag 26 28 30
Harsh
26.50


## 5- Lists

In [5]:
N = int(input())
L = []
for i in range (N) :
    line = input().split()
    command = line[0]
    if command == 'insert' :
        L.insert(int(line[1]), int(line[2]))
    elif command == 'print' :
        print(L)
    elif command == 'remove' :
        L.remove(int(line[1]))
    elif command == 'append' :
        L.append(int(line[1]))
    elif command == 'sort' :
        L.sort()
    elif command == 'pop' :
        L.pop(-1)
    elif command == 'reverse' :
        L.reverse()

12
insert 0 5
insert 1 10
insert 0 6
print
[6, 5, 10]
remove 6
append 9
append 1
sort
print
[1, 5, 9, 10]
pop
reverse
print
[9, 5, 1]


## 6- Tuples

In [6]:
n = int(input())
integer_list = map(int, input().split())
print(hash(tuple(integer_list)))

2
1 2
-3550055125485641917


# 

# Strings 

## 1- sWAP cASE

In [24]:
def swap_case(s):
    s = list(s)
    for i in range (len(s)) :
        if s[i].isupper() :
            s[i] = s[i].lower()
        elif s[i].islower() :
            s[i] = s[i].upper()        
    return ''.join(s)

s = 'HackerRank.com presents "Pythonist 2".'
result = swap_case(s)
print(result)

hACKERrANK.COM PRESENTS "pYTHONIST 2".


## 2- String Split and Join

In [25]:
def split_and_join(line):
    line = line.split(" ")
    return "-".join(line)

line = 'this is a string'
result = split_and_join(line)
print(result)

this-is-a-string


## 3- What's Your Name?

In [27]:
def print_full_name(first, last):
    print('Hello '+first+' '+last+'! You just delved into python.')
    
print_full_name('Ross', 'Taylor')

Hello Ross Taylor! You just delved into python.


## 4- Mutations

In [29]:
def mutate_string(string, position, character):
    return string[:position]+character+string[position+1:]

s = 'abracadabra'
i, c = 5, 'k'
s_new = mutate_string(s, int(i), c)
print(s_new)

abrackdabra


## 5- Find a string

In [30]:
def count_substring(string, sub_string):
    count = 0
    for i in range (len(string)-len(sub_string)+1) :
        if string[i:i+len(sub_string)] == sub_string :
            count += 1
    return count

string = 'ABCDCDC'
sub_string = 'CDC'    
count = count_substring(string, sub_string)
print(count)

2


## 6- String Validators

In [31]:
s = 'qA2'
print(any(a.isalnum() for a in s))
print(any(a.isalpha() for a in s))
print(any(a.isdigit() for a in s))
print(any(a.islower() for a in s))
print(any(a.isupper() for a in s))

True
True
True
True
True


## 7- Text Alignment

In [1]:
thickness = 5 #This must be an odd number
c = 'H'

#Top Cone
for i in range(thickness):
    print((c*i).rjust(thickness-1)+c+(c*i).ljust(thickness-1))

#Top Pillars
for i in range(thickness+1):
    print((c*thickness).center(thickness*2)+(c*thickness).center(thickness*6))

#Middle Belt
for i in range((thickness+1)//2):
    print((c*thickness*5).center(thickness*6))    

#Bottom Pillars
for i in range(thickness+1):
    print((c*thickness).center(thickness*2)+(c*thickness).center(thickness*6))    

#Bottom Cone
for i in range(thickness):
    print(((c*(thickness-i-1)).rjust(thickness)+c+(c*(thickness-i-1)).ljust(thickness)).rjust(thickness*6))


    H    
   HHH   
  HHHHH  
 HHHHHHH 
HHHHHHHHH
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHHHHHHHHHHHHHHHHHHHHHH   
  HHHHHHHHHHHHHHHHHHHHHHHHH   
  HHHHHHHHHHHHHHHHHHHHHHHHH   
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
                    HHHHHHHHH 
                     HHHHHHH  
                      HHHHH   
                       HHH    
                        H     


## 8- Text Wrap

In [2]:
import textwrap

def wrap(string, max_width):
    return textwrap.fill(string,max_width)

string, max_width = 'ABCDEFGHIJKLIMNOQRSTUVWXYZ', 4
result = wrap(string, max_width)
print(result)

ABCD
EFGH
IJKL
IMNO
QRST
UVWX
YZ


## 9- Designer Door Mat

In [3]:
#N, M = list(map(int,input().split()))
N, M = 7, 21
k = 1
for i in range (1,N+1) :
    if i <= N//2 :
        print((k*'.|.').center(M,'-'))
        k += 2
    elif i > N//2+1 :
        k -= 2
        print((k*'.|.').center(M,'-'))
    else :
        print('WELCOME'.center(M,'-'))

---------.|.---------
------.|..|..|.------
---.|..|..|..|..|.---
-------WELCOME-------
---.|..|..|..|..|.---
------.|..|..|.------
---------.|.---------


## 10- String Formatting

In [10]:
def print_formatted(number):
    width = len(bin(number))-2
    for i in range (1,number+1) :
        print(str(i).rjust(width),end = ' ')
        print(str("%o"%i).rjust(width),end=' ')
        print(str("%X"%i).rjust(width),end=' ')
        print(format(i,"b").rjust(width))
        
n = 17
print_formatted(n)

    1     1     1     1
    2     2     2    10
    3     3     3    11
    4     4     4   100
    5     5     5   101
    6     6     6   110
    7     7     7   111
    8    10     8  1000
    9    11     9  1001
   10    12     A  1010
   11    13     B  1011
   12    14     C  1100
   13    15     D  1101
   14    16     E  1110
   15    17     F  1111
   16    20    10 10000
   17    21    11 10001


## 11- Alphabet Rangoli

In [25]:
def print_rangoli(size):
    alphabet = list(map(chr, range(97, 123)))
    width = size*4-3
    for i in range(1,size*2) :
        if i <= size :
            letters = alphabet[size-i:size]
            reverse_letters = letters.copy()
            reverse_letters.reverse()
            print('-'.join(reverse_letters).rjust(width//2+1,'-')+'-'.join(letters)[1:].ljust(width//2,'-'))
        else :
            i = size*2-i
            letters = alphabet[size-i:size]
            reverse_letters = letters.copy()
            reverse_letters.reverse()
            print('-'.join(reverse_letters).rjust(width//2+1,'-')+'-'.join(letters)[1:].ljust(width//2,'-'))
        
    
n = 5
print_rangoli(n)

--------e--------
------e-d-e------
----e-d-c-d-e----
--e-d-c-b-c-d-e--
e-d-c-b-a-b-c-d-e
--e-d-c-b-c-d-e--
----e-d-c-d-e----
------e-d-e------
--------e--------


## 12- Capitalize!

In [34]:
def solve(s):
    for name in s.split() :
        s = s.replace(name, name.capitalize())
    return s

solve('chris alan')

'Chris Alan'

## 13- The Minion Game

In [36]:
def minion_game(string):
    stuart_score = 0
    kevin_score = 0
    for i in range (len(string)) :
        c = string[i]
        if c != 'A' and c != 'E' and c != 'I' and c != 'O' and c != 'U' :
            stuart_score += len(string)-i
        elif c.isalpha() :
            kevin_score += len(string)-i
    if stuart_score > kevin_score :
        print("Stuart "+str(stuart_score))
    elif kevin_score > stuart_score :
        print("Kevin "+str(kevin_score))
    else :
        print("Draw")
        
s = 'BANANA'
minion_game(s)

Stuart 12


## 14- Merge the Tools!

In [44]:
def merge_the_tools(string, k):
    for i in range (1, len(string)+1) :
        if i%k == 0 :
            s = ''
            for c in string[i-k:i] :
                if c not in s :
                    s += c
            print(s)    
    
    
string, k = 'AAABCADDE', 3
merge_the_tools(string, k)

A
BCA
DE


# 

# Sets

## 1- Introduction to Sets

In [9]:
def average(array):
    distinct_heights = set(array)
    return(round(sum(distinct_heights)/len(distinct_heights),3))

average([161,182,161,154,176,170,167,171,170,174])

169.375

## 2- No Idea!

In [10]:
n,m = 3,2
array = [1,5,3]
A = set([3,1])
B = set([5,7])


happiness = 0
for i in array :
    if i in A :
        happiness += 1
    elif i in B :
        happiness -= 1
print(happiness)

1


## 3- Symmetric Difference

In [11]:
M = 4
a = set([2,4,5,9])
N = 4
b = set([2,4,11,12])

diff = b.difference(a).union(a.difference(b))

for n in sorted(diff) :
    print(n)
    

5
9
11
12


## 4- Set.add()

In [1]:
set = set()
for i in range (int(input())) :
    set.add(input())
print(len(set))

7
UK
CHINA
USA
FRANCE
NEW ZEALAND
UK
FRANCE
5


## 5- Set .discard(), .remove() & .pop()

In [3]:
n = 9
s = set([1,2,3,4,5,6,7,8,9])

for i in range(10) :
    line = input().split()
    command = line[0]
    if command == 'remove' :
        s.remove(int(line[1]))
    elif command == 'discard' :
        s.discard(int(line[1]))
    elif command == 'pop' :
        s.pop()
print(sum(s))

pop
remove  9
discard 9
discard 8
remove 7
pop
discard 6
remove 5
pop
discard 5
4


## 6- Set .union() Operation

In [4]:
n = 9
students_english_newspaper = set([1,2,3,4,5,6,7,8,9])
m = 9
students_french_newspaper = set([10,1,2,3,11,21,55,6,8])
print(len(students_english_newspaper.union(students_french_newspaper)))

13


## 7- Set .intersection() Operation

In [5]:
n = 9
students_english_newspaper = set([1,2,3,4,5,6,7,8,9])
m = 9
students_french_newspaper = set([10,1,2,3,11,21,55,6,8])
print(len(students_english_newspaper.intersection(students_french_newspaper)))

5


## 8- Set .difference() Operation

In [7]:
n = 9
students_english_newspaper = set([1,2,3,4,5,6,7,8,9])
m = 9
students_french_newspaper = set([10,1,2,3,11,21,55,6,8])
print(len(students_english_newspaper.difference(students_french_newspaper)))

4


## 9- Set .symmetric_difference() Operation

In [8]:
n = 9
students_english_newspaper = set([1,2,3,4,5,6,7,8,9])
m = 9
students_french_newspaper = set([10,1,2,3,11,21,55,6,8])
print(len(students_english_newspaper.symmetric_difference(students_french_newspaper)))

8


## 10- Set Mutations

In [ ]:
n = int(input())
A = set(map(int,input().split()))

for i in range(int(input())) :
    command = input().split()[0]
    if command == 'update' :
        A.update(set(map(int,input().split())))
    elif command == 'intersection_update' :
        A.intersection_update(set(map(int,input().split())))
    elif command == 'difference_update' :
        A.difference_update(set(map(int,input().split())))
    elif command == 'symmetric_difference_update' :
        A.symmetric_difference_update(set(map(int,input().split())))
print(sum(A))

## 11- The Captain's Room

In [9]:
K = 5
L = [1,2,3,6,5,4,4,2,5,3,6,1,6,5,3,2,4,1,2,5,1,4,3,6,8,4,3,1,5,6,2]
old_set = set(L)
for i in old_set :
    L.remove(i)
new_set = set(L)
print(old_set.difference(new_set).pop())

8


## 12- Check Subset

In [ ]:
T = int(input())
for i in range (T) :
    n = int(input())
    A = set(map(int,input().split()))
    m = int(input())
    B = set(map(int,input().split()))
    if B >= A :
        print(True)
    else :
        print(False)

## 13- Check Strict Superset

In [ ]:
A = set(map(int,input().split()))
n = int(input())
for i in range (n) :
    S = set(map(int,input().split()))
    if not(A > S) :
        print(False)
        exit()
print(True)

# 

# Collections

## 1- collections.Counter()

In [ ]:
from collections import Counter

X = int(input())
L = list(map(int,input().split()))
shoe_counter = Counter(L)
money = 0
for i in range (int(input())) :
    line = list(map(int,input().split()))
    size = line[0]
    price = line[1]
    if size in shoe_counter.keys() :
        money += price
        L.remove(size)
        shoe_counter = Counter(L)
print(money)

## 2- DefaultDict Tutorial

In [ ]:
from collections import defaultdict

n,m = map(int,input().split())
dictA = defaultdict(list)
for i in range (n) :
    dictA[input()].append(str(i+1))
for i in range(m) :
    word = input()
    if len(dictA[word]) != 0 :
        print(' '.join(dictA[word]))
    else :
        print(-1)

## 3- Collections.namedtuple()

In [ ]:
from collections import namedtuple

N = int(input())
Student = namedtuple('Student',input())
Students = []
for i in range (N) :
    values = input().split()
    Students.append(Student(values[0], values[1], values[2], values[3]))
sum = 0
for Student in Students :
    sum += int(Student.MARKS)
print(round(sum/N,2))

## 4- Collections.OrderedDict()

In [ ]:
from collections import OrderedDict

N = int(input())
ordered_dict = OrderedDict()
for i in range(N) :
    line = input().split()
    item_name = ' '.join(line[:-1])
    if item_name in ordered_dict.keys() :
        ordered_dict[item_name] += int(line[-1])
    else :
        ordered_dict[item_name] = int(line[-1])  
        
for item_name,net_price in ordered_dict.items() :
    print(item_name,net_price)

## 5- Word Order

In [ ]:
import collections

N = int(input())

L = []
for i in range (N) :
    L.append(input())
word_counter = collections.Counter(L)
print(len(word_counter))
print(' '.join(map(str,word_counter.values())))

## 6- Collections.deque()

In [ ]:
from collections import deque

N = int(input())
d = deque()
for i in range(N) :
    line = input().split()
    command = line[0]
    if command == 'append' :
        d.append(line[1])
    elif command == 'appendleft' :
        d.appendleft(line[1])
    elif command == 'pop' :
        d.pop()
    elif command == 'popleft' :
        d.popleft()
print(' '.join(d))

## 7- Company Logo

In [25]:
from collections import Counter
characters = 'aabbbccde'
counter_characters = Counter(sorted(characters)
for key,value in counter_characters.most_common(3) :
    print(key,value)

b 3
a 2
c 2


## 8- Piling Up!

In [ ]:
from collections import deque

N = int(input())
for i in range (N) :
    n = int(input())
    d = deque(map(int,input().split()))
    answer = 'Yes'
    if d[0]>=d[-1] :
        max = d[0]
    else :
        max = d[-1]
    N = len(d)
    for j in range (N-1) :
        if d[0]>d[-1] :
            element = d.popleft()
        else :
            element = d.pop()
        if max>=element :
            max = element
        else :
            answer = 'No'
            break
    print(answer)

# 

# Date and Time

## 1- Calendar Module

In [2]:
import calendar

#date = list(map(int,input().split()))
date = [8, 5, 2015]

day_index = calendar.weekday(date[2], date[0], date[1])

days_dict = {'0':'MONDAY', '1':'TUESDAY', '2':'WEDNESDAY', '3':'THURSDAY', '4':'FRIDAY', '5':'SATURDAY', '6':'SUNDAY'}

print(days_dict[str(day_index)])

WEDNESDAY


## 2- Time Delta

In [30]:
from datetime import datetime, timedelta

def time_delta(t1, t2):
    format = "%a %d %b %Y %H:%M:%S %z"
    time1 = datetime.strptime(t1, format)
    time2 = datetime.strptime(t2, format)
    time_delta = abs(time1-time2)
    return(str(int(time_delta.total_seconds())))

time_delta("Sat 02 May 2015 19:54:36 +0530","Fri 01 May 2015 13:54:36 -0000")

'88200'

# 

# Exceptions

In [2]:
N = int(input())

for i in range (N) :
        try :
            a,b = map(int,input().split())
            print(int(a)//int(b))
        except ZeroDivisionError as e :
            print("Error Code:",e)
        except ValueError as e :
            print("Error Code:",e)

3
1 0
Error Code: integer division or modulo by zero
2 $
Error Code: invalid literal for int() with base 10: '$'
3 1
3


# 

# Built-ins

## 1- Zipped

In [3]:
N,X = map(int,input().split())
MARKS = []
for i in range (X) :
    MARKS += [list(map(float,input().split()))]
for mark_student in zip(*MARKS) :
    print(sum(mark_student)/X)

5 3
89 90 78 93 80
90 91 85 88 86  
91 92 83 89 90.5
90.0
91.0
82.0
90.0
85.5


## 2- Athlete Sort

In [5]:
nm = input().split()

n = int(nm[0])

m = int(nm[1])

arr = []

for _ in range(n):
    arr.append(list(map(int, input().rstrip().split())))

k = int(input())

athletes = sorted(arr, key=lambda attribute:attribute[k])
for athlete in athletes :
    print(' '.join(map(str,athlete)))

5 3
10 2 5
7 1 0
9 9 9
1 23 12
6 5 9
1
7 1 0
10 2 5
6 5 9
9 9 9
1 23 12


## 3- ginortS

In [6]:
input = input()
lowercase_characters = sorted([k for k in list(input) if k.islower()])
uppercase_characters = sorted([k for k in list(input) if k.isupper()])
odd_digits = sorted([k for k in list(input) if k.isdigit() and int(k)%2==1])
even_digits = sorted([k for k in list(input) if k.isdigit() and int(k)%2==0])
print(''.join(lowercase_characters+uppercase_characters+odd_digits+even_digits))

Sorting1234
ginortS1324


# 

# Python Functionals

In [32]:
cube = lambda x: x**3

def fibonacci(n):
    if n == 0 :
        return []
    elif n == 1 :
        return [0]
    L = [0,1]
    for i in range(2,n+1) :
        L.append(L[i-2]+L[i-1])
    return L[:n]

print(list(map(cube, fibonacci(5))))

[0, 1, 1, 8, 27]


# 

# Regex and Parsing challenges 

## 1- Detect Float Point Number

In [3]:
import re

pattern = "^[-+]?[0-9]*\.[0-9]+$"
for i in range (int(input())) :
    string = input()
    print(bool(re.match(pattern, string)))


4
4.0O0
False
-1.00
True
+4.54
True
SomeRandomStuff
False


## 2- Re.split()

In [4]:
regex_pattern = r"[,.]+"

import re
print("\n".join(re.split(regex_pattern, input())))

100,000,000.000
100
000
000
000


## 3- Group(), Groups() & Groupdict()

In [4]:
import re

m = re.search(r'([a-zA-Z0-9])\1+',input())
if m is not None :
    print(m.group(1))
else :
    print(-1)

..12345678910111213141516171820212223
1


## 4- Re.findall() & Re.finditer()

In [16]:
import re

strings = re.findall(r'(?<=[QWRTYPSDFGHJKLZXCVBNMqwrtypsdfghjklzxcvbnm])[AEIOUaeiou]{2,}(?=[QWRTYPSDFGHJKLZXCVBNMqwrtypsdfghjklzxcvbnm])', input())

if len(strings) != 0 :
    print('\n'.join(strings))
else :
    print(-1)

rabcdeefgyYhFjkIoomnpOeorteeeeet
ee
Ioo
Oeo
eeeee


## 5- Re.start() & Re.end()

In [17]:
import re

S = input()
k = re.compile(input())
m = k.search(S)

if m is None :
    print((-1,-1))
while m :
    print((m.start(), m.end()-1))
    m = k.search(S,m.start()+1)

aaadaa
aa
(0, 1)
(1, 2)
(4, 5)


## 6- Regex Substitution

In [18]:
import re

N = int(input())

for i in range (N) :
    line = input()
    # we need to call the substitution function for each case two times to correctly substitute two consecutives ' && ' or ' || '
    line = re.sub(r'\ \&\&\ ', " and ", line)
    line = re.sub(r'\ \&\&\ ', " and ", line)
    line = re.sub(r'\ \|\|\ ', " or ", line)
    line = re.sub(r'\ \|\|\ ', " or ", line)
    print(line)

1
&& &&&& && && || |||| || ||
&& &&&& and and or |||| or ||


## 7- Validating Roman Numerals

In [19]:
regex_pattern = r"^M{0,3}(CM|CD|D?C{0,3})(XC|XL|L?X{0,3})(IX|IV|V?I{0,3})$"	# Do not delete 'r'.

import re
print(str(bool(re.match(regex_pattern, input()))))

CDXXI
True


## 8- Validating phone numbers

In [21]:
import re

regex = r'^(7|8|9){1}[0-9]{9}$'
for i in range (int(input())) :
    if re.search(regex,input()) is not None :
        print('YES')
    else :
        print('NO')

2
9587456281
YES
1252478965
NO


## 9- Validating and Parsing Email Addresses

In [22]:
import email.utils
import re

regex = r'^[a-zA-Z][a-zA-Z0-9-._]+@[a-zA-Z]+\.([a-zA-Z]){1,3}$'
for i in range (int(input())) :
    line = input()
    email_parsing = email.utils.parseaddr(line)
    if email_parsing[0] != '' and email_parsing[1] != '' and bool(re.match(regex, email_parsing[1])) :
            print(line)    

2
DEXTER <dexter@hotmail.com>
DEXTER <dexter@hotmail.com>
VIRUS <virus!@variable.:p>


## 10- Hex Color Code

In [ ]:
import re

N = int(input())
check = False
regex = r'#[0-9A-Fa-f]{3,6}'
for i in range (N) :
    line = input()
    if '{' in line :
        check = True
    elif '}' in line :
        check = False
    else :
        if check :
            hex_colors_codes = re.findall(regex,line)
            [print(hex_color_code) for hex_color_code in hex_colors_codes if len(hex_color_code) == 4 or len(hex_color_code) == 7]

## 11- HTML Parser - Part 1

In [ ]:
from html.parser import HTMLParser

# create a subclass and override the handler methods
class MyHTMLParser(HTMLParser):
    def handle_starttag(self, tag, attrs):
        print("Start :",tag)
        for attr in attrs :
            print('->',attr[0],'>',attr[1])
    def handle_endtag(self, tag):
        print("End   :",tag)
    def handle_startendtag(self, tag, attrs):
        print("Empty : "+tag)
        for attr in attrs :
            print('->',attr[0]+' >',attr[1])
            
parser = MyHTMLParser()
for i in range (int(input())) :
    parser.feed(input())    

## 12- HTML Parser - Part 2

In [ ]:
from html.parser import HTMLParser

class MyHTMLParser(HTMLParser):
    def handle_comment(self, data):
        if '\n' in data :
            print(">>> Multi-line Comment\n"+data)
        else :
            print(">>> Single-line Comment\n"+data)
    def handle_data(self, data):
        if '\n' not in data :
            print(">>> Data\n"+data)
 
  
html = ""       
for i in range(int(input())):
    html += input().rstrip()
    html += '\n'
    
parser = MyHTMLParser()
parser.feed(html)
parser.close()

## 13- Detect HTML Tags, Attributes and Attribute Values

In [ ]:
from html.parser import HTMLParser

class MyHTMLParser(HTMLParser):
    def handle_starttag(self, tag, attrs):
        print(tag)
        for attr in attrs :
            print('->',attr[0],'>',attr[1])

            
parser = MyHTMLParser()
for i in range (int(input())) :
    parser.feed(input()) 

## 14- Validating UID

In [6]:
import re

for i in range (int(input())) :
    uid = input()
    if uid.isalnum() and len(uid) == 10 and bool(re.search(r'(.*[A-Z]){2,}',uid)) and bool(re.search(r'(.*[0-9]){3,}',uid)) and len(set(uid)) == len(uid) :
        print('Valid')
    else :
        print('Invalid')

2
B1CD102354
Invalid
B1CDEF2354
Valid


## 15- Validating Credit Card Numbers

In [ ]:
import re

for i in range (int(input())) :
    card_number = input()
    if bool(re.search(r'\d{4}-\d{4}-\d{4}-\d{4}',card_number)) :
        card_number = ''.join(card_number.split('-'))
    if bool(re.search(r'^[456]',card_number)) and len(card_number)==16 and bool(re.search(r'[0-9]{16}',card_number)) and not(bool(re.search(r'(\d)\1{3,}',card_number))) :
        print('Valid')
    else :
        print('Invalid')

## 16- Validating Postal Codes

In [7]:
regex_integer_in_range = r"^[1-9][0-9]{5}$"	# Do not delete 'r'.
regex_alternating_repetitive_digit_pair = r"(\d)(?=\d\1)"	# Do not delete 'r'.

import re
P = input()

print (bool(re.match(regex_integer_in_range, P)) 
and len(re.findall(regex_alternating_repetitive_digit_pair, P)) < 2)

110000
False


## 17- Matrix Script

In [9]:
import re

first_multiple_input = input().rstrip().split()

n = int(first_multiple_input[0])

m = int(first_multiple_input[1])

matrix = []

for _ in range(n):
    matrix_item = input()
    matrix.append(matrix_item)
matrix_script = ''
for i in range(m) :
    matrix_script += ''.join([str[i] for str in matrix])
print(re.sub(r'(?<=[a-zA-Z0-9])[\ !@#$%&]+(?=[a-zA-Z0-9])', ' ', matrix_script))

7 3
Tsi
h%x
i #
sM 
$a 
#t%
ir!
This is Matrix#  %!


# 

# XML

## 1 - Find the Score

In [ ]:
import sys
import xml.etree.ElementTree as etree

def get_attr_number(node):
    score = 0
    for child in node.iter() :
        score += len(child.attrib)
    return score

if __name__ == '__main__':
    sys.stdin.readline()
    xml = sys.stdin.read()
    tree = etree.ElementTree(etree.fromstring(xml))
    root = tree.getroot()
    print(get_attr_number(root))

## 2 - Find the Maximum Depth

In [ ]:
import xml.etree.ElementTree as etree

maxdepth = 0
def depth(elem, level):
    global maxdepth
    
    if maxdepth == level  :
        maxdepth += 1
    
    for child_node in elem :
            depth(child_node,level+1)
    
if __name__ == '__main__':
    n = int(input())
    xml = ""
    for i in range(n):
        xml =  xml + input() + "\n"
    tree = etree.ElementTree(etree.fromstring(xml))
    depth(tree.getroot(), -1)
    print(maxdepth)

# 

# Closures and Decorations

## 1- Standardize Mobile Number Using Decorators

In [ ]:
def wrapper(f):
    def fun(l):
        f(["+91 "+c[-10:-5]+" "+c[-5:] for c in l])
    return fun

@wrapper
def sort_phone(l):
    print(*sorted(l), sep='\n')

if __name__ == '__main__':
    l = [input() for _ in range(int(input()))]
    sort_phone(l) 

## 2- Name Directory

In [1]:
import operator

def person_lister(f):
    def inner(people):
        people = sorted(people, key=lambda x:int(x[2]))
        return [f(person) for person in people]
    return inner

@person_lister
def name_format(person):
    return ("Mr. " if person[3] == "M" else "Ms. ") + person[0] + " " + person[1]

people = [input().split() for i in range(int(input()))]
print(*name_format(people), sep='\n')

3
Mike Thomson 20 M
Robert Bustle 32 M
Andria Bustle 30 F
Mr. Mike Thomson
Ms. Andria Bustle
Mr. Robert Bustle


# 

# Numpy

## 1- Arrays

In [1]:
import numpy

def arrays(arr):
    # complete this function
    # use numpy.array
    array = numpy.array(arr, float)
    return numpy.flip(array)
    

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


## 2- Shape and Reshape

In [2]:
import numpy

inputs = input().split()
array = numpy.array(inputs, int)
array.shape = (3,3)
print(array)

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## 3- Transpose and Flatten

In [1]:
import numpy

n_lines, m_columns = input().split()
L = []
for i in range (int(n_lines)) :
    L += input().split()
array = numpy.array(list(map(int,L)), int)
array.shape = (int(n_lines), int(m_columns))

print(numpy.transpose(array))
print(array.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


## 4- Concatenate

In [2]:
import numpy

N, M, P = input().split()
array_1 = []
for i in range (int(N)) :
    array_1.append(list(map(int,input().split())))
array_2 = []
for i in range (int(M)) :
    array_2.append(list(map(int,input().split())))
    
array_3 = numpy.concatenate((array_1, array_2))
array_3.shape = (int(N)+int(M), int(P))
print(array_3)

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


## 5- Zeros and Ones

In [3]:
import numpy

shape_integers = tuple(map(int,input().split()))
print(numpy.zeros(shape_integers, int))
print(numpy.ones(shape_integers, int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


## 6- Eye and Identity

In [4]:
import numpy

numpy.set_printoptions(legacy='1.13')

N, M = input().split()
print(numpy.eye(int(N), int(M)))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


## 7- Array Mathematics

In [5]:
import numpy

N, M = map(int,input().split())
A = []
for i in range (N) :
    A.append(input().split())
array_A = numpy.array(A, int)
B = []
for i in range (N) :
    B.append(input().split())
array_B = numpy.array(B, int)

print(array_A + array_B)
print(array_A - array_B)
print(array_A * array_B)
print(array_A // array_B)
print(array_A % array_B)
print(array_A ** array_B)

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


## 8- Floor, Ceil and Rint

In [7]:
import numpy

numpy.set_printoptions(legacy='1.13')

array = numpy.array(input().split(),float)
print(numpy.floor(array))
print(numpy.ceil(array))
print(numpy.rint(array))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


## 9- Sum and Prod

In [9]:
import numpy

N, M = input().split()
L = []
for i in range (int(N)) :
    L += input().split()
    
array = numpy.array(L, int)
array.shape = (int(N), int(M))
sum_array = numpy.sum(array, axis = 0)
print(numpy.prod(sum_array))

2 2
1 2
3 4
24


## 10- Min and Max

In [10]:
import numpy

N, M = input().split()
L = []
for i in range (int(N))  :
    L.append(input().split())
array = numpy.array(L, int)
array.shape = (int(N), int(M))
min_array = numpy.min(array, axis = 1)
print(numpy.max(min_array))

4 2
2 5
3 7
1 3
4 0
3


## 11- Mean, Var, and Std

In [11]:
import numpy

N, M = input().split()
L = []
for i in range (int(N))  :
    L.append(input().split())
array = numpy.array(L, int)
array.shape = (int(N), int(M))

print(numpy.mean(array, axis = 1))
print(numpy.var(array, axis = 0))
print(round(numpy.std(array), 11))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


## 12- Dot and Cross

In [12]:
import numpy

N = int(input())

A = []
for i in range (N) :
    A.append(input().split())
array_A = numpy.array(A, int)
array_A.shape = (N, N)

B = []
for i in range (N) :
    B.append(input().split())
array_B = numpy.array(B, int)
array_B.shape = (N, N)

print(numpy.dot(array_A, array_B))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


## 13- Inner and Outer

In [13]:
import numpy

array_A = numpy.array(input().split(), int)
array_B = numpy.array(input().split(), int)
print(numpy.inner(array_A, array_B))
print(numpy.outer(array_A, array_B))

0 1
2 3
3
[[0 0]
 [2 3]]


## 14- Polynomials

In [14]:
import numpy

coefficients = list(map(float,input().split()))
x = int(input())
print(numpy.polyval(coefficients,x))

1.1 2 3
0
3.0


## 15- Linear Algebra

In [15]:
import numpy

N = int(input())
A = []
for i in range (N) :
    A.append(list(map(float,input().split())))

print(round(numpy.linalg.det(A), 2))

2
1.1 1.1
1.1 1.1
0.0
